production:
  host: localhost
  port: 9010
  pid_file: log/ferret.pid
  log_file: log/ferret_server.log
  log_level: warn

development:
  host: localhost
  port: 9010
  pid_file: log/ferret.pid

test:
  host: localhost
  port: 9009
  pid_file: log/ferret.pid
